---
title: "停止（提前退出程序）"
date: 2023-11-01T20:12:31+08:00
---

我们将在本章中讨论的最后一类流控制语句是暂停。暂停是终止程序的流控制语句。在C++中，暂停被实现为函数（而不是关键字），因此我们的暂停语句将是函数调用。

让我们绕一个简短的弯路，回顾一下当程序正常退出时会发生什么。当main（）函数返回时（通过到达函数末尾或通过返回语句），会发生许多不同的事情。

首先，因为我们要离开函数，所以所有局部变量和函数参数都会被销毁（通常）。

接下来，调用一个名为std:：exit（）的特殊函数，并将main（）（状态代码）的返回值作为参数传入。那么什么是std:：exit（）？

***
## std:：exit（）函数

exit（）是一个导致程序正常终止的函数。正常终止意味着程序以预期的方式退出。请注意，术语正常终止并不意味着程序是否成功（这就是状态代码的含义）。例如，假设您正在编写一个程序，希望用户输入要处理的文件名。如果用户键入了无效的文件名，则程序可能会返回非零状态代码来指示故障状态，但它仍然具有正常的终止。

exit（）执行许多清理函数。首先，销毁具有静态存储持续时间的对象。然后，如果使用了任何文件，则执行其他一些杂项文件清理。最后，将控制返回给操作系统，并将参数传递给std:：exit（）用作状态代码。

***
## 显式调用std:：exit（）

尽管在函数main（）结束时隐式调用std:：exit（），但也可以显式调用std:：exit。当以这种方式调用std:：exit（）时，需要包含cstdlib头。

下面是显式使用std:：exit（）的示例：

```C++
#include <cstdlib> // for std::exit()
#include <iostream>

void cleanup()
{
    // code here to do any kind of cleanup required
    std::cout << "cleanup!\n";
}

int main()
{
    std::cout << 1 << '\n';
    cleanup();

    std::exit(0); // terminate and return status code 0 to operating system

    // The following statements never execute
    std::cout << 2 << '\n';

    return 0;
}
```

该程序打印：

请注意，调用std:：exit（）后的语句从不执行，因为程序已经终止。

尽管在上面的程序中，我们从函数main（）中调用std:：exit（），但可以从任何函数中调用std:：exit（）来终止程序。

关于显式调用std:：exit（）的一个重要注意事项：std::exit（.）不会清理任何局部变量（在当前函数中，或在调用堆栈上的函数中）。因此，通常最好避免调用std:：exit（）。

{{< alert success >}}
**警告**

std:：exit（）函数不清理当前函数中的局部变量或调用堆栈。

{{< /alert >}}

***
## 标准：：atexit

由于std:：exit（）立即终止程序，因此您可能希望在终止之前手动进行一些清理。在这种情况下，清理意味着关闭数据库或网络连接、释放分配的任何内存、将信息写入日志文件等…

在上面的示例中，我们调用了函数cleanup（）来处理清理任务。然而，记住在每次调用exit（）之前手动调用清理函数会给程序员增加负担。

为了帮助实现这一点，C++提供了std:：atexit（）函数，它允许您指定一个函数，该函数将在程序终止时通过std::exit（）自动调用。

下面是一个示例：

```C++
#include <cstdlib> // for std::exit()
#include <iostream>

void cleanup()
{
    // code here to do any kind of cleanup required
    std::cout << "cleanup!\n";
}

int main()
{
    // register cleanup() to be called automatically when std::exit() is called
    std::atexit(cleanup); // note: we use cleanup rather than cleanup() since we're not making a function call to cleanup() right now

    std::cout << 1 << '\n';

    std::exit(0); // terminate and return status code 0 to operating system

    // The following statements never execute
    std::cout << 2 << '\n';

    return 0;
}
```

该程序的输出与前面的示例相同：

那你为什么要这么做？它允许您在一个地方（可能在main中）指定清理函数，然后不必担心在调用std:：exit（）之前记住显式调用该函数。

这里关于std:：atexit（）和清理函数的几点注意事项：首先，由于在main（）终止时隐式调用std:：exit（），因此如果程序以这种方式退出，这将调用std::atexit）注册的任何函数。其次，正在注册的函数必须没有参数，并且没有返回值。最后，如果需要，可以使用std:：atexit（）注册多个清理函数，它们将按注册的相反顺序调用（最后注册的函数将首先调用）。

{{< alert success >}}
**相关内容**

在第20.1课——函数指针中，我们讨论了将函数作为参数传递。

{{< /alert >}}

{{< alert success >}}
**对于高级读者**

在多线程程序中，调用std:：exit（）可能会导致程序崩溃（因为调用std::exit（。）的线程将清理可能仍然被其他线程访问的静态对象）。由于这个原因，C++引入了另一对函数，它们的工作方式类似于std:：exit（）和std:：atexit（），称为std::quick_exit（和std:∶at_quick_exit（）。std:：quick_exit（）通常会终止程序，但不会清理静态对象，并且可以或不可以执行其他类型的清理。对于以std:：quick_exit（）终止的程序，std::at_quick_exit（）执行与std:∶atexit（）相同的角色。

{{< /alert >}}

***
## 标准：：abort和标准：：terminate

C++包含另外两个与暂停相关的函数。

函数的作用是：abort（）导致程序异常终止。异常终止意味着程序出现某种异常运行时错误，程序无法继续运行。例如，尝试除以0将导致异常终止。std:：abort（）不执行任何清理。

```C++
#include <cstdlib> // for std::abort()
#include <iostream>

int main()
{
    std::cout << 1 << '\n';
    std::abort();

    // The following statements never execute
    std::cout << 2 << '\n';

    return 0;
}
```

在本章后面的部分中，我们将看到隐式调用std:：abort的情况（8.18--Assert和static_Assert）。

std:：terminate（）函数通常与异常一起使用（我们将在后面的一章中介绍异常）。尽管可以显式调用std:：terminate，但在未处理异常时（以及在其他一些与异常相关的情况下），它更经常被隐式调用。默认情况下，std:：terminate（）调用std::abort（）。

***
## 你应该什么时候停车？

简短的回答是“几乎从不”。销毁局部对象是C++的一个重要部分（特别是当我们进入类时），并且上面提到的函数都不能清理局部变量。异常是处理错误情况的更好、更安全的机制。

{{< alert success >}}
**最佳做法**

只有在没有安全的方法从主功能正常返回时才使用停止。如果尚未禁用异常，则更喜欢使用异常来安全地处理错误。

{{< /alert >}}

